### ISSUE TITLE
Incorrect Strong Number in Two Verses

### ISSUE THREAD

**Issue by ephraim-sefaria** [openscriptures/morphhb#18]
Hi, 
I'm not sure if this repository is still being worked on, but I've found that in two places, II Chronicles 28:3 and I Kings 17:14 the Tetragrammaton has a completely wrong Strong Number listed in the attribute for that word.

**Comment by DavidTroidl** [comment]
I found and corrected the one in 1 Kings.  2 Chronicles was already correct in my local copy.  I have uploaded the updates.
