### ISSUE TITLE
WLC version 4.20

### ISSUE THREAD

**Issue by digitalmoran** [openscriptures/morphhb#19]
I recently discovered this project. Since the activity level has decreased, I was wondering if anyone is already working on updating the WLC with the changes released in version 4.20?

**Comment by dowens76** [comment]
Good question. I have not worked on it for awhile. It would be nice to see the project continue. But I can check with someone and see what our process was for updating to subsequent versions of WLC.

**Comment by DavidTroidl** [comment]
The update has been made.
