### ISSUE TITLE
How are Conflicts Identified

### ISSUE THREAD

**Issue by limitedAtonement** [openscriptures/morphhb#20]
Is there currently a way to see words whose parsing conflicts between users? I have been parsing and labelled a couple things differently from whoever came before me. Who is going to find that conflict? Should we be diverting parsers to those passages especially?

Thanks for the good work on this project. It is currently very easy to contribute, and took me all of 15 or 20 minutes to get rolling.

**Comment by DavidTroidl** [comment]
Conflicts are recorded in the database.  They are intended to be 
verified by an editor.


On 5/20/2016 2:53 PM, limitedAtonement wrote:
>
> Is there currently a way to see words whose parsing conflicts between 
> users? I have been parsing and labelled a couple things differently 
> from whoever came before me. Who is going to find that conflict? 
> Should we be diverting parsers to those passages especially?
>
> Thanks for the good work on this project. It is currently very easy to 
> contribute, and took me all of 15 or 20 minutes to get rolling.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/openscriptures/morphhb/issues/20>
>



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by DavidHaslam** [comment]
Suggest close this issue #20

**Comment by dowens76** [comment]
@limitedAtonement If you have done some parsing on a significant section, let me know the passage. I can take a look at your work. Also, if you contact us through the Google Group (https://groups.google.com/forum/#!forum/openscriptures-hb) and introduce yourself we can talk further. As we see contributors making solid contributions (especially if they have some academic background in Hebrew), then we promote them to editors. But we need to know you.
