### ISSUE TITLE
Where are Data Stored?

### ISSUE THREAD

**Issue by limitedAtonement** [openscriptures/morphhb#21]
I'm happy to be parsing and adding information into this Open Scriptures project, but where are the data going? Where can I view the data as compiled so far?

**Comment by DavidTroidl** [comment]
The data is stored in the database of the parsing site.  Once verified, 
they can be included in a release of the XML files.


On 5/20/2016 2:54 PM, limitedAtonement wrote:
>
> I'm happy to be parsing and adding information into this Open 
> Scriptures project, but where are the data going? Where can I view the 
> data as compiled so far?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/openscriptures/morphhb/issues/21>
>



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by DavidHaslam** [comment]
Suggest close this issue #21
