### ISSUE TITLE
preposition + pronominal suffix combos incorrectly given lemma of 1992

### ISSUE THREAD

**Issue by AndyHubert** [openscriptures/morphhb#35]
The following outlier form-lemma combos should not have the /1992 in their lemmas since these are normally considered pronominal suffixes. (262 occurrences)

וְ/כָ/הֵם c/k/1992
וְ/לָ/הֶם c/l/1992
וּ/מֵ/הֶם c/m/1992
כָ/הֵם k/1992
כָּ/הֵם k/1992
לָ/הֶם l/1992
לָ/הֶן l/1992
מֵ/הֶם m/1992

I can correct these in the parsing data and so they will reflect the correct lemmas on export.

**Comment by DavidTroidl** [comment]
The first instance only occurs once, in 2Sam 24:3.  It is listed the same way in the Interlinear Bible on WORDsearch.   The Theological Wordbook of the Old Testament points out:
Unlike the singular, the third person plural forms occasionally combine with prepositions, "by them" (Habakkuk 1:16, etc.).
Theological Wordbook of the Old Testament.
So this does not seem like something we can categorically decide.

**Comment by AndyHubert** [comment]
I should have pointed out that the two big ones are לָ/הֶם and מֵ/הֶם. The former form appears 638 times and according to the ETCBC is always parsed as a preposition with a suffix. But it has the lemma of `l/1992` in 159 of these occurrences (the others simply have a lemma of `l`). The latter appears 92 times, 90 of which have the `m/1992` lemma and 2 have the simple `m` lemma, but once again they all are parsed as a preposition with a suffix in the ETCBC.

Given that we have likewise parsed them as a preposition + suffix, I was making this suggestion so that our lemmas and parsings would be consistent.

**Comment by DavidTroidl** [comment]
I would think the presence of the he-tsere on the 1st, 4th and 5th forms is a good indication that they should be left as they are.  The others, with the he-segol, could probably be changed, as a blanket parsing, and left to the discretion of the editors.

**Comment by AndyHubert** [comment]
Will do.

**Comment by AndyHubert** [comment]
I believe that three of these were inadvertently updated to a lemma of `l` or `m` but should not have been:

Jer 10:2 - מֵ/הֵֽמָּה
Jer 14:16 - לָ/הֵ֔מָּה
Eccl 12:12 - מֵ/הֵ֖מָּה

Given the ה at the end of the form, I believe these should be restored to the lemma `l/1992`. Thoughts?

**Comment by DavidTroidl** [comment]
Yes, thanks for catching that.

**Comment by DavidTroidl** [comment]
I just made the corrections.
