### ISSUE TITLE
Change מאת to always have a lemma of m/854 (versus m/853)?

### ISSUE THREAD

**Issue by AndyHubert** [openscriptures/morphhb#37]
After noticing that you had changed a few instances of this sort in recent updates, I took a look at the situation in general and had a conversation with Joel via the parsing project slack:

Me: This form (with or without suffix) currently has a lemma of `m/853` (direct object marker) 147 times in our data, and a lemma of `m/854` (preposition) 26 times. Given your suggestion that we would parse this as two prepositions in all cases, should the lemma for all of them be `m/854`?

Joel: Yes, that is correct.  Languages do weird things sometimes, but as far as I know, the direct object marker *never* attaches to the preposition מִן in Hebrew.  All these cases should be labeled m/854 and NOT m/853.

Thoughts?

**Comment by DavidTroidl** [comment]
I've been dealing with these when I came across them.  It makes sense that they should all be changed.  I found 150 instances of m/853.  It appears with a suffix in Gen 26:27, which should also be m/854.  In view of this discussion, we should change all m/853 to m/854.

**Comment by DavidTroidl** [comment]
The changes have been made.
