### ISSUE TITLE
Parsing inseparable prepositions with the definite article

### ISSUE THREAD

**Issue by dowens76** [openscriptures/morphhb#4]
Currently the schema parses inseparable prepositions with the article in a strange way that could cause problems. As an example, consider:
לַ/חֹ֣דֶשׁ
The lemma is l/2320. This term includes two segments, the preposition and the noun. It's parsing, however, would involve three: HR/Tp/Ncmsa.
Perhaps it would be better to parse the definite article as an attribute of the preposition, so: HRd/Ncmsa, the Rd representing "preposition with the definite article."

**Comment by DavidTroidl** [comment]
This has been resolved in the Hebrew Morphology Codes.
