### ISSUE TITLE
missing entries in VerseMap.xml

### ISSUE THREAD

**Issue by eliranwong** [openscriptures/morphhb#54]
In the books of 1Kings, there should be verse breaks in WLC in 18:34, 20:3 and 22:21 to map KJV versification.  22:44 of WLC should be mapped to part "b" of 22:43 in KJV.

I did not find them in VerseMap.xml in "WLC" folder.

A screenshot for an example attached (English text = KJV; Hebrew Interlinear built from latest OSHB).
![img_1098](https://user-images.githubusercontent.com/25262722/40292772-2d3e44ee-5cc5-11e8-9586-a6c9c9497a83.jpg)

**Comment by DavidTroidl** [comment]
Thank you for pointing these out.  The corrections have been made, and the VerseMap updated.
