### ISSUE TITLE
Textual issue in Num 27:5

### ISSUE THREAD

**Issue by joeldruark** [openscriptures/morphhb#66]
It appears that two whole words plus one letter have been left off the end of the Hebrew text of Num 27:5.  The term _mishpata_ should include a nun suffix followed by the words _liphney yhwh_.

**Comment by DavidTroidl** [comment]
Correct. Here is the XML:

        <verse osisID="Num.27.5">
          <w lemma="c/7126" morph="HC/Vhw3ms" id="04XkU">וַ/יַּקְרֵ֥ב</w>
          <w lemma="4872" n="0.0.0" morph="HNp" id="04ga6">מֹשֶׁ֛ה</w>
          <w lemma="853" morph="HTo" id="041sG">אֶת</w><seg type="x-maqqef">־</seg><w lemma="4941" n="0.0" morph="HNcmsc/Sp3fp" id="04DbS">מִשְׁפָּטָ֖/<seg type="x-large">ן</seg></w>
          <note n="5">Large letter(s). Shown as large letters without a superscript note number. </note>
          <w lemma="l/6440" morph="HR/Ncbpc" id="04EX3">לִ/פְנֵ֥י</w>
          <w lemma="3068" n="0" morph="HNp" id="04vV1">יְהוָֽה</w><seg type="x-sof-pasuq">׃</seg>
          <seg type="x-samekh">ס</seg>
        </verse>
Note: the nun is a large letter. Where are you seeing the problem?

**Comment by joeldruark** [comment]
I'm seeing the problem on the "Read" page.  Somehow the large letter is interfering with the text display, I guess, because that letter is missing as well as the rest of the verse.  I wonder if the same thing happens with other large letters, too?

**Comment by DavidTroidl** [comment]
The missing suffix is an issue with the Read application. I am working on that. If the following two word are also missing, that may be a browser issue. What are you using to view the page?

I checked out all the instances of large, small and suspended letters, and cataloged the issue with them: Lev.11.42, Num.27.5, Deut.6.4, Deut.6.4, Judg.18.30, Isa.44.14, Jer.39.13, Ps.80.14, Prov.16.28, Job.38.13, Job.38.15. Each one has a note number 5, 6 or 7.

**Comment by joeldruark** [comment]
I'm using Google Chrome.  If I use the Safari browser on my Mac computer, the final two words show but not the nun suffix (although I do see the "5" footnote caller.

**Comment by DavidTroidl** [comment]
Done. I tested all the affected verses in Firefox. Numbers 27:5 works in Vivaldi, based on Chromium. I don't use Chrome or Safari. Thanks for all your help. Let me know if everything is fine, and we can close the issue.

**Comment by joeldruark** [comment]
![Screen Shot 2019-09-19 at 7 24 59 AM](https://user-images.githubusercontent.com/34244019/65215861-51527080-daaf-11e9-80af-ffa59e8401ec.jpg)
Here's what Num 27:5 looks like now using Google Chrome.

**Comment by joeldruark** [comment]
![Screen Shot 2019-09-19 at 7 32 04 AM](https://user-images.githubusercontent.com/34244019/65215955-ae4e2680-daaf-11e9-98c7-71fbad5e2d81.jpg)
Here's what it looks like with Safari.  Looks like it's OK here...

**Comment by jag3773** [comment]
I can confirm that this is working on Firefox (69.0) on Mac.  Chrome (Version 76.0.3809.132 & 77.0.3865.90) on Mac also shows it correctly for me:
<img width="521" alt="Screen Shot 2019-09-19 at 8 54 40 AM" src="https://user-images.githubusercontent.com/107731/65245831-50bfd700-dabb-11e9-87f9-18df4ae5bdf0.png">

@joeldruark What version of Chrome are you using?

**Comment by DavidTroidl** [comment]
Jesse,
Thank you for checking. I was going to try to do that at school.
Joel,
My first thought was the browser may be remembering the old page. I have this sometimes with Firefox. I can't just "clear the cache" as in the old days. It has a history that remembers these things, and sometimes doesn't accept changes. Then I have to tell the history to forget the page, and start again from scratch. While I was working on the fix, something like that happened, but when I opened other books and then went back to Numbers 27:5, it showed the changes. Try going to Jeremiah 39:13 and see if that looks okay. Then come back to Numbers. Hope this helps.

**Comment by joeldruark** [comment]
I have a really old Mac (purchased in 2014, updated to High Sierra 10.13.6), and I can't tell what version of Chrome I'm using.  When I click on the "About" menu, it shows me 79.0.3906, but it's asking me to update to it, so I don't think that's the version I'm actually running.  But if it looks correct for you, Jesse, then it seems likely that the issue I have is related to my browser/computer.

**Comment by DavidTroidl** [comment]
Time to close this issue.
