### ISSUE TITLE
Systemic parsing error for כֻּלֹּה

### ISSUE THREAD

**Issue by joeldruark** [openscriptures/morphhb#67]
The term כֻּלֹּה should be parsed as lemma=“כֹּל”, strong=“H3605”, morph=“He,Ncmsc:Sp3ms”. 
 Currently, the suffix is consistently parsed as 3fs.  In some of these instances, the BHS indicates K/Q variants where the WLC does not.

Here is a total list (that I could find) of attestations that need to be examined and/or changed: 2 Sam 2:9; Isa 15:3; Jer 2:21, 8:6,10(x2), 15:10, 20:7, 48:31,38, 50:13; Ezek 11:15, 20:40, 29:2, 35:15, 36:10; Hos 13:2; Hab 1:9,15.

**Comment by DavidTroidl** [comment]
I searched the OSHB and confirm most of these.  
Jer.50.13, Ezek.29.2 and Ezek.35.15 look like the feminine form.  
I would also propose Isa.16.7 and Nah.2.1.  
I am in favor of the change, once we can agree on the instances.  
Any other opinions?

**Comment by dowens76** [comment]
I agree Jer.50.13, Ezek.29.2 and Ezek.35.15 have the feminine suffix form.

You mean that Isa 16:7 and Nah 2:1 are the masculine form, right? If so, I agree.

**Comment by joeldruark** [comment]
I also agree: Jer 50:13, Ezek 29:2, and Ezek 35:15 are feminine; Isa 16:7 and Nah 2:1 are masculine.  Thanks for double-checking the list, David.

**Comment by DavidIB** [comment]
In the Tyndale House data it is marked as Fem. at Jer.50.13; Ezek.29.2; 35.15. 

It also has another couple of masc forms at Isa.16.7; Nahum 1.2

See the tagged Hebrew at https://tyndale.github.io/STEPBible-Data/

 

David IB


 <https://tyndalehouse.com/> 


David Instone-Brewer


Snr Research Fellow in New Testament & Rabbinics and Technical Director for  <https://www.stepbible.org/> STEPBible.org

	

 <mailto:technical@tyndalehouse.com> technical@tyndalehouse.com          +44 1223 566601


Tyndale House, Cambridge, CB3 9BA, UK    <https://www.facebook.com/TyndaleHouseCambridge/>    <https://twitter.com/tyndale_house>    

	

Company No. 9437542 Reg. Charity No. 1161396 VAT Reg. No. GB 221 7195 27

**Comment by DavidTroidl** [comment]
The corrections have been made. Thanks to everyone.
