### ISSUE TITLE
Submitting Corrections

### ISSUE THREAD

**Issue by jcuenod** [openscriptures/morphhb#74]
I'm not sure the best way to submit corrections but:

On line 6550 In https://github.com/openscriptures/morphhb/blob/master/wlc/Exod.xml, it looks to me as though the Ketiv should be a *niphal* (not a *hiphil*—which is the Qere reading).

I'm happy to submit a PR but I guess that this is being pulled from some other source (if so, I failed to find that source).

**Comment by DavidTroidl** [comment]
The correction is made. Thanks for submitting it.
