### ISSUE TITLE
separate lemmas for 738a and 738b?

### ISSUE THREAD

**Issue by joeldruark** [openscriptures/morphhb#78]
The specific location that prompts this Issue is the K/Q variant in Lam 3:10, where two different forms of the Hebrew word for "lion" [אֲרִי and אַרְיֵה] are both parsed as the lemma "738a."  BDB and HALOT both appear to consider these as distinct Hebrew lexemes with different (although semantically related) etymological derivations.  This seems supported by the fact that the one term exhibits morphological inflection in the text whereas the other does not.  I suggest making a change to this effect in the lemma identification throughout the OSHB, distinguishing between "738a" (for אֲרִי) and "738b" (for אַרְיֵה).

**Comment by DavidTroidl** [comment]
The correction is made. All the other instances of 738 appear correct.
