### ISSUE TITLE
K/Q in Exo 21:8

### ISSUE THREAD

**Issue by joeldruark** [openscriptures/morphhb#81]
It looks to me like the K/Q variant in Exodus 21:8 is not labeled like all the others are.  The Qere is shown in black text, whereas all other Qere readings are usually shown in blue text on the OSHB Read page.

**Comment by DavidTroidl** [comment]
This comes from the coloring for the segmentation. Normally, prefixes are blue, with a word in black. Here the "word" would be blue, so the prefix becomes black.

**Comment by joeldruark** [comment]
Oh, I got it.  There is no "word" in this case.
