### ISSUE TITLE
Merging Proper Nouns to Match Strong's Numbers

### ISSUE THREAD

**Issue by jonathanrobie** [openscriptures/morphhb#86]
In the syntax trees, I am merging proper nouns so that all of the words that correspond to a given Strong's number are combined.   If you want this upstream, I am happy to contribute it, if you don't, I will continue to do this downstream.

Example:  תּ֣וּבַל קַ֔יִן (Tubal-Cain) in Genesis 4:22:

וְצִלָּ֣ה גַם־הִ֗וא יָֽלְדָה֙ אֶת־תּ֣וּבַל קַ֔יִן לֹטֵ֕שׁ כָּל־חֹרֵ֥שׁ נְחֹ֖שֶׁת וּבַרְזֶ֑ל וַֽאֲח֥וֹת תּֽוּבַל־קַ֖יִן נַֽעֲמָֽה׃

Our resources combine this to make one name, corresponding to one lexicon entry.  For instance, here is what it looks like in an Enhanced Resource:

![image](https://user-images.githubusercontent.com/1767869/126184816-650ca45c-7b25-407e-9b41-d148e342e813.png)

In the existing OSHB, these are represented by lemmas that end with a + marker, indicating that you need to add further words before you have something that matches the entire lemma:

```xml
          <w lemma="3205" n="1.2.0" morph="HVqp3fs" id="01pDQ">יָֽלְדָה֙</w>
          <w lemma="853" morph="HTo" id="01deG">אֶת</w><seg type="x-maqqef">־</seg><w lemma="8423+" morph="HNp" id="01Nvj">תּ֣וּבַל</w>
          <w lemma="8423" n="1.2" morph="HNp" id="01Gye">קַ֔יִן</w>
          <w lemma="3913" n="1.1" morph="HVqrmsc" id="01qCo">לֹטֵ֕שׁ</w>
```

In my trees, I am merging them.  There is a single `w` for 

```xml
<w lemma="8423+" morph="HNp HNp" id="01Nvj">תּ֣וּבַל קַ֔יִן</w>
```

Do you want that upstream, or should I continue to make this change when I use your upstream?

**Comment by DavidTroidl** [comment]
I'd rather keep it downstream.
It would conflict with cantillation interpretation and word segmentation. We are not set up to deal with spaces within a w element.

**Comment by jonathanrobie** [comment]
Thanks, I'll close this issue then.
