### ISSUE TITLE
Dead Link to HebrewMorphologyCodes - github.io vs. github.com

### ISSUE THREAD

**Issue by jonathanrobie** [openscriptures/morphhb#89]
This page:

https://hb.openscriptures.org/

Contains a link to this page:

https://openscriptures.github.com/morphhb/parsing/HebrewMorphologyCodes.html

Which gives a 404 error.  Changing "github.com" to "github.io" fixes the error.

https://openscriptures.github.io/morphhb/parsing/HebrewMorphologyCodes.html

Could someone please fix the page in the repo?

**Comment by jonathanrobie** [comment]
And while you're at it, try this:

```
morphbb $  grep -r "github.com" .
```

I see other similar broken links.

**Comment by DavidTroidl** [comment]
Fixed. There were to links for Hebrew Morphology Codes on the Morphology page. I didn't find any other broken links.
